# Generated by Django 3.0.3 on 2020-04-02 08:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educator', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='course_pictures')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='accounts.Category')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='educator.Educator')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(null=True, upload_to='course_pictures/module_pictures')),
                ('title', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='course.Course')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='educator.Educator')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(null=True, upload_to='course_pictures/module_pictures/lesson_pictures')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('title', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='course.Course')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='course.Module')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='educator.Educator')),
            ],
        ),
    ]
