# Generated by Django 3.0.3 on 2020-04-02 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True)),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='parent', serialize=False, to='accounts.UserProfile')),
                ('short_bio', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='student.Student')),
            ],
        ),
    ]
