# Generated by Django 3.0.3 on 2020-04-02 08:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('educator', '0001_initial'),
        ('parent', '0001_initial'),
        ('student', '0001_initial'),
        ('accounts', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='achievement_pictures')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('FSTC', 'From Student to Course'), ('FSTE', 'From Student to Educator'), ('FPTE', 'From Parent to Educator'), ('FETS', 'From Educator to Student'), ('FCTS', 'From Course to Student')], max_length=4)),
                ('updated_at', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_achievements', to='accounts.UserProfile')),
                ('related_courses', models.ManyToManyField(blank=True, related_name='achievements', to='course.Course')),
                ('related_educators', models.ManyToManyField(blank=True, related_name='achievements', to='educator.Educator')),
                ('related_parents', models.ManyToManyField(blank=True, related_name='achievements', to='parent.Parent')),
                ('related_students', models.ManyToManyField(blank=True, related_name='achievements', to='student.Student')),
            ],
        ),
    ]
