# Generated by Django 3.0.3 on 2020-04-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together={('course', 'student')},
        ),
    ]
