# Generated by Django 3.0.3 on 2020-04-02 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='educator', serialize=False, to='accounts.UserProfile')),
                ('local_connect', models.BooleanField(default=False)),
                ('online_connect', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('short_bio', models.TextField(blank=True, null=True)),
                ('show_in_listings', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('categories', models.ManyToManyField(related_name='educators', to='accounts.Category')),
            ],
        ),
    ]
